# Development Environment Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iam_db
    username: iam_user
    password: your_password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  data:
    redis:
      host: localhost
      port: 6379
      password: ""

# JWT Configuration for Development
jwt:
  secret: dev-super-secret-jwt-key-for-development-environment-only
  expiration-ms: 86400000  # 24 hours
  refresh-expiration-ms: 604800000  # 7 days

# Auth Configuration for Development
auth:
  max-login-attempts: 3  # Stricter for testing
  account-lock-duration-minutes: 5  # Shorter for development
  password-reset-token-expiry-hours: 1
  email-verification-token-expiry-hours: 24

# Logging Configuration
logging:
  level:
    com.iam.auth: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.redis: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/iam-auth-service-dev.log

# Management endpoints for development
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always