server:
  port: 8082

spring:
  application:
    name: iam-auth-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope:
              - openid
              - email
              - profile
            redirect-uri: ${OAUTH2_REDIRECT_URI:http://localhost:8082}/login/oauth2/code/google
            authorization-grant-type: authorization_code
            client-name: Google

          github:
            client-id: ${GITHUB_CLIENT_ID:your-github-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:your-github-client-secret}
            scope:
              - user:email
              - read:user
            redirect-uri: ${OAUTH2_REDIRECT_URI:http://localhost:8082}/login/oauth2/code/github
            authorization-grant-type: authorization_code
            client-name: GitHub

          facebook:
            client-id: ${FACEBOOK_CLIENT_ID:your-facebook-client-id}
            client-secret: ${FACEBOOK_CLIENT_SECRET:your-facebook-client-secret}
            scope:
              - email
              - public_profile
            redirect-uri: ${OAUTH2_REDIRECT_URI:http://localhost:8082}/login/oauth2/code/facebook
            authorization-grant-type: authorization_code
            client-name: Facebook

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            user-name-attribute: sub

          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id

          facebook:
            authorization-uri: https://www.facebook.com/v18.0/dialog/oauth
            token-uri: https://graph.facebook.com/v18.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email
            user-name-attribute: id

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-super-secret-jwt-key-that-should-be-at-least-256-bits}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}  # 24 hours
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000}  # 7 days

# Auth Configuration
auth:
  max-login-attempts: ${AUTH_MAX_LOGIN_ATTEMPTS:5}
  account-lock-duration-minutes: ${AUTH_ACCOUNT_LOCK_DURATION:30}
  password-reset-token-expiry-hours: ${AUTH_PASSWORD_RESET_EXPIRY:1}
  email-verification-token-expiry-hours: ${AUTH_EMAIL_VERIFICATION_EXPIRY:24}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.iam.auth: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"