spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/iam_test_db
    username: iam_test_user
    password: test_password

  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      database: 1  # Use different database for tests

# JWT Configuration for Testing
jwt:
  secret: test-jwt-secret-key-for-testing-environment-only
  expiration-ms: 60000  # 1 minute for faster testing
  refresh-expiration-ms: 300000  # 5 minutes for testing

# Auth Configuration for Testing
auth:
  max-login-attempts: 2  # Low for testing lockout scenarios
  account-lock-duration-minutes: 1  # Very short for testing

# Logging Configuration for Testing
logging:
  level:
    com.iam.auth: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    org.springframework.data.redis: DEBUG